version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for Elm
  - package-ecosystem: "elm"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "elm"
    directory: "/review"
    schedule:
      interval: "daily"
